# Generated by Django 5.1.2 on 2024-11-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "клиент", "verbose_name_plural": "клиенты"},
        ),
    ]
