# Generated by Django 5.1.2 on 2024-11-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messages_list", "0002_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "сообщение", "verbose_name_plural": "сообщения"},
        ),
    ]
