# Generated by Django 5.1.2 on 2024-11-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="clients.client",
            ),
        ),
    ]
