# Generated by Django 5.1.2 on 2024-11-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_mailingattempt_recipient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingattempt",
            name="recipient",
        ),
    ]
